# Generated by Django 2.2.7 on 2019-12-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='display_name',
            new_name='language',
        ),
    ]
